### ISSUE TITLE
Length of domain name address including padding?

### ISSUE THREAD

**Issue by studentmain** [45G/socks6-draft#4]
I'm trying to implement a socks6 server based on draft11. I have a question about domain name in address field.

>       *  Domain Name: one byte that contains the length of the FQDN,
>          followed by the FQDN itself.  The string is not NUL-terminated,
>          but padded by NUL characters, if needed.

When a FQDN is padded, should it's length including those padding NUL?

For example, when domain name is example.com, and padded with 1 NUL, address field should be `12 example.com 0` or `11 example.com 0`?

**Comment by vlolteanu** [comment]
It's the former (`12 example.com 0`). If the client adds zeroes at the end of the FQDN, it must count them as well. Otherwise, the proxy has no idea where the address actually ends.

I'll explain this better in the next revision. Thanks for catching this ambiguity.
